permalink: /:year/:month/:day/:title/

# where you plan to publish your site
url: http://umbccyberdawgs.github.io
# any subdirectory that appears after the domain where you're publishing your site
baseurl: "/resources"
# this property is useful for conditional filtering of content that is separate from the PDF.
output: web
# this appears on the top navigation bar next to the home button
topnav_title: UMBC Cyber Dawgs Resources
# this appears in the html browser tab for the site title (seen mostly by search engines, not users)
site_title: Compilation of resources for getting into cybersecurity
# this appears in the footer
company_name: UMBC Cyber Defense Team
# if you're using Github, provide the basepath to the branch you've created for reviews, following the sample here. if not, leave this value blank.
github_editme_path: UMBCCyberDawgs/resources
# if you're using disqus for comments, add the shortname here. if not, leave this value blank.
disqus_shortname: idrbwjekyll
# the preview server used. Leave as is.
host: 127.0.0.1
# the port where the preview is rendered. You can leave this as is unless you have other Jekyll builds using this same port that might cause conflicts.
port: 4005

# these are the files and directories that jekyll will exclude from the build
exclude:
  - _site
  - _drafts/
  - .idea/


feedback_disable: True
#feedback_email: umbccd@gmail.com
#feedback_text: "Need help?"
#feedback_link: "http://helpy.io/"
# change feedback link behaviour if you use a support ticketing system or something else

highlighter: rouge
# library used for syntax highlighting

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge
# filter used to process markdown. note that kramdown differs from github-flavored markdown in some subtle ways

collections:
  tooltips:
    output: false
# collection declared here. this renders the content in _tooltips and processes it, but doesn't output it as actual files in the output.

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
      sidebar: home_sidebar
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true

  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
      search: true
      sidebar: tags_sidebar

# these are defaults used for the frontmatter for these file types


description: "The UMBC Cyber Defense Team's resource wiki. This contains all information that we have found important compiled into one resource."
# the description is used in the feed.xml file
