permalink: /:year/:month/:day/:title/

url: http://umbccd.umbc.edu
baseurl: "/resources"
output: web
topnav_title: UMBC Cyber Dawgs Resources
site_title: Compilation of resources for getting into cybersecurity
company_name: UMBC Cyber Defense Team
description: "The UMBC Cyber Defense Team's resource wiki. This contains all information that we have found important compiled into one resource."
host: 127.0.0.1
port: 4005

exclude:
  - _site
  - _drafts/
  - .git

highlighter: rouge

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: true
 hard_wrap: false
 syntax_highlighter: rouge

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      sidebar: home_sidebar
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      tooltip: true

